// <auto-generated />
using System;
using GovUK.Dfe.FlexForms.Prism.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GovUK.Dfe.FlexForms.Prism.Data.Migrations
{
    [DbContext(typeof(PrismDbContext))]
    partial class PrismDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("prism")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GovUK.Dfe.FlexForms.Prism.Data.Entities.AnswerFactEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("application_id");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("data_type");

                    b.Property<string>("FieldId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("field_id");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("generation_id");

                    b.Property<string>("InterpretationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("interpretation_status");

                    b.Property<bool?>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_completed");

                    b.Property<string>("ItemId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("item_id");

                    b.Property<int?>("ItemOrdinal")
                        .HasColumnType("int")
                        .HasColumnName("item_ordinal");

                    b.Property<byte[]>("LogicalKeyHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .HasColumnName("logical_key_hash")
                        .IsFixedLength();

                    b.Property<string>("NestedPath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("nested_path");

                    b.Property<string>("OccurrencePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("occurrence_path");

                    b.Property<string>("ParentFieldId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("parent_field_id");

                    b.Property<string>("RawValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<bool?>("ValueBool")
                        .HasColumnType("bit")
                        .HasColumnName("value_bool");

                    b.Property<DateOnly?>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.Property<DateTime?>("ValueDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("value_date_time");

                    b.Property<decimal?>("ValueDecimal")
                        .HasPrecision(38, 10)
                        .HasColumnType("decimal(38,10)")
                        .HasColumnName("value_decimal");

                    b.Property<string>("ValueJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value_json");

                    b.Property<string>("ValueString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value_string");

                    b.HasKey("Id");

                    b.HasIndex("GenerationId", "LogicalKeyHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "FieldId");

                    b.ToTable("answer_facts", "prism");
                });

            modelBuilder.Entity("GovUK.Dfe.FlexForms.Prism.Data.Entities.ApplicationProjectionState", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("application_id");

                    b.Property<Guid?>("ActiveGenerationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("active_generation_id");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("int")
                        .HasColumnName("contract_version");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("lifecycle");

                    b.Property<DateTime>("ProjectedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("projected_at");

                    b.Property<int>("ProjectorVersion")
                        .HasColumnType("int")
                        .HasColumnName("projector_version");

                    b.Property<Guid?>("ResponseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("response_id");

                    b.Property<byte[]>("SourceHash")
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .HasColumnName("source_hash")
                        .IsFixedLength();

                    b.Property<DateTime?>("SourceOccurredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("source_occurred_at");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("source_revision");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("template_id");

                    b.Property<Guid?>("TemplateVersionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("template_version_id");

                    b.HasKey("TenantId", "ApplicationId");

                    b.HasIndex("ActiveGenerationId");

                    b.HasIndex("TenantId", "ProjectedAt");

                    b.ToTable("application_projection_state", "prism");
                });

            modelBuilder.Entity("GovUK.Dfe.FlexForms.Prism.Data.Entities.BackfillOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("operation_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<int>("MessagesEnqueued")
                        .HasColumnType("int")
                        .HasColumnName("messages_enqueued");

                    b.Property<DateTime?>("ModifiedSince")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_since");

                    b.Property<int>("PagesProcessed")
                        .HasColumnType("int")
                        .HasColumnName("pages_processed");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("requested_by");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("OperationId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("backfill_operations", "prism");
                });

            modelBuilder.Entity("GovUK.Dfe.FlexForms.Prism.Data.Entities.DeletionTombstone", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("recorded_at");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("source_revision");

                    b.HasKey("TenantId", "ApplicationId");

                    b.ToTable("deletion_tombstones", "prism");
                });

            modelBuilder.Entity("GovUK.Dfe.FlexForms.Prism.Data.Entities.FieldCatalogEntry", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TemplateVersionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("template_version_id");

                    b.Property<string>("FieldId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("field_id");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("int")
                        .HasColumnName("contract_version");

                    b.Property<string>("ChoicesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("choices_json");

                    b.Property<string>("ControlType")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("control_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("data_type");

                    b.Property<string>("ExportStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("export_status");

                    b.Property<int?>("FieldOrder")
                        .HasColumnType("int")
                        .HasColumnName("field_order");

                    b.Property<string>("FlowId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("flow_id");

                    b.Property<string>("FlowMode")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("flow_mode");

                    b.Property<bool>("IsCollection")
                        .HasColumnType("bit")
                        .HasColumnName("is_collection");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<string>("Label")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("label");

                    b.Property<string>("PageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("page_id");

                    b.Property<string>("PageTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("page_title");

                    b.Property<string>("ParentFieldId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("parent_field_id");

                    b.Property<string>("SemanticKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("semantic_key");

                    b.Property<string>("Sensitivity")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("sensitivity");

                    b.Property<string>("TaskGroupId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("task_group_id");

                    b.Property<string>("TaskGroupName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("task_group_name");

                    b.Property<string>("TaskId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("task_id");

                    b.Property<string>("TaskName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("task_name");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("template_id");

                    b.Property<string>("TemplateVersionNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("template_version_number");

                    b.HasKey("TenantId", "TemplateVersionId", "FieldId", "ContractVersion");

                    b.HasIndex("TenantId", "TemplateId", "FieldId");

                    b.ToTable("field_catalog", "prism");
                });

            modelBuilder.Entity("GovUK.Dfe.FlexForms.Prism.Data.Entities.FieldExportPolicy", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("template_id");

                    b.Property<string>("FieldId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("field_id");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("decided_by");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("decision");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("int")
                        .HasColumnName("policy_version");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("reason");

                    b.HasKey("TenantId", "TemplateId", "FieldId");

                    b.ToTable("field_export_policy", "prism");
                });

            modelBuilder.Entity("GovUK.Dfe.FlexForms.Prism.Data.Entities.ProjectionGeneration", b =>
                {
                    b.Property<Guid>("GenerationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("generation_id");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("activated_at");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("application_id");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("int")
                        .HasColumnName("contract_version");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("ExportPolicyVersion")
                        .HasColumnType("int")
                        .HasColumnName("export_policy_version");

                    b.Property<int>("FactCount")
                        .HasColumnType("int")
                        .HasColumnName("fact_count");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("kind");

                    b.Property<int>("ProjectorVersion")
                        .HasColumnType("int")
                        .HasColumnName("projector_version");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("response_id");

                    b.Property<long?>("ResponseRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("response_revision");

                    b.Property<byte[]>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .HasColumnName("source_hash")
                        .IsFixedLength();

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("source_revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("submission_id");

                    b.Property<DateTime?>("SupersededAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("superseded_at");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("template_id");

                    b.Property<Guid>("TemplateVersionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("template_version_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.HasKey("GenerationId");

                    b.HasIndex("Status", "SupersededAt");

                    b.HasIndex("TenantId", "ApplicationId", "Kind", "Status");

                    b.ToTable("projection_generations", "prism");
                });

            modelBuilder.Entity("GovUK.Dfe.FlexForms.Prism.Data.Entities.SchemaInfo", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("schema_info", "prism");

                    b.HasData(
                        new
                        {
                            Key = "contract_version",
                            Value = "1"
                        });
                });

            modelBuilder.Entity("GovUK.Dfe.FlexForms.Prism.Data.Entities.SubmissionSnapshot", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("submission_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("application_id");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("int")
                        .HasColumnName("contract_version");

                    b.Property<DateTime>("ProjectedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("projected_at");

                    b.Property<int>("ProjectorVersion")
                        .HasColumnType("int")
                        .HasColumnName("projector_version");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("response_id");

                    b.Property<long?>("ResponseRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("response_revision");

                    b.Property<Guid>("SelectedGenerationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("selected_generation_id");

                    b.Property<byte[]>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("binary(32)")
                        .HasColumnName("source_hash")
                        .IsFixedLength();

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("source_revision");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("template_id");

                    b.Property<Guid>("TemplateVersionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("template_version_id");

                    b.HasKey("TenantId", "SubmissionId");

                    b.HasIndex("SelectedGenerationId");

                    b.HasIndex("TenantId", "ApplicationId");

                    b.HasIndex("TenantId", "SubmittedAt");

                    b.ToTable("submission_snapshots", "prism");
                });

            modelBuilder.Entity("GovUK.Dfe.FlexForms.Prism.Data.Entities.AnswerFactEntity", b =>
                {
                    b.HasOne("GovUK.Dfe.FlexForms.Prism.Data.Entities.ProjectionGeneration", "Generation")
                        .WithMany("Facts")
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Generation");
                });

            modelBuilder.Entity("GovUK.Dfe.FlexForms.Prism.Data.Entities.ApplicationProjectionState", b =>
                {
                    b.HasOne("GovUK.Dfe.FlexForms.Prism.Data.Entities.ProjectionGeneration", "ActiveGeneration")
                        .WithMany()
                        .HasForeignKey("ActiveGenerationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ActiveGeneration");
                });

            modelBuilder.Entity("GovUK.Dfe.FlexForms.Prism.Data.Entities.SubmissionSnapshot", b =>
                {
                    b.HasOne("GovUK.Dfe.FlexForms.Prism.Data.Entities.ProjectionGeneration", "SelectedGeneration")
                        .WithMany()
                        .HasForeignKey("SelectedGenerationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SelectedGeneration");
                });

            modelBuilder.Entity("GovUK.Dfe.FlexForms.Prism.Data.Entities.ProjectionGeneration", b =>
                {
                    b.Navigation("Facts");
                });
#pragma warning restore 612, 618
        }
    }
}
